import Head from "next/head";
import { Outfit } from "@next/font/google";
// import { ChakraProvider } from "@chakra-ui/react";

const outfit = Outfit();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.className}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {/* <ChakraProvider>{children}</ChakraProvider> */}
        {children}
      </body>
    </html>
  );
}
